snort:
  rule_config: /etc/snort/rules/local.rules
  base_rule_config: /etc/snort/rules/rules.tmpl
  interface: h1-eth0
  address: 10.0.0.1

truffle:
  address: '0.0.0.0'
  port: 8082

pigrelay:
  alert_server:
    address: http://192.168.1.1
    port: 8081
  socket_file: "/tmp/snort_alert"

onos:
  address: http://192.168.1.1
  port: 8181
